{% set name = "neo4j-connector" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d648144911af73dfb504fea3ba54080e3660876f5af6055d4c6be9768a28f78a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests <3.0,>=2.0

test:
  imports:
    - neo4j

about:
  home: https://github.com/textkernel/neo4j-connector
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This library contains everything you need to execute single-request transactions for Neo4j 3.0
           and above through its HTTP API
  doc_url: https://neo4j-connector.readthedocs.io/en/latest
  dev_url: https://github.com/textkernel/neo4j-connector

extra:
  recipe-maintainers:
    - Tata17
    - oblute
    - rluria14
